#!/usr/bin/env python3
"""Generate zh-CN.json from en.json using a hand-written translation map."""
import json
import os
import sys

BASE = os.path.join(os.path.dirname(__file__), '..', 'locales')
en_path = os.path.join(BASE, 'en.json')
zh_path = os.path.join(BASE, 'zh-CN.json')

with open(en_path, encoding='utf-8') as f:
    en = json.load(f)

# Chinese translations mapped by key
zh = {
    # common
    "common.save": "保存",
    "common.saving": "保存中…",
    "common.saved": "已保存",
    "common.cancel": "取消",
    "common.edit": "编辑",
    "common.delete": "删除",
    "common.loading": "加载中…",
    "common.active": "启用",
    "common.disabled": "已禁用",
    "common.disabled_lc": "已禁用",
    "common.name": "名称",
    "common.url": "网址",
    "common.none": "无",

    # nav
    "nav.dashboard": "仪表盘",
    "nav.monitors": "监控项",
    "nav.statusPages": "状态页",
    "nav.incidents": "事件",
    "nav.notifications": "通知",
    "nav.config": "设置",

    # theme / layout
    "theme.toLightMode": "切换到浅色模式",
    "theme.toDarkMode": "切换到深色模式",
    "layout.signOut": "退出登录",

    # login
    "login.username": "用户名",
    "login.password": "密码",
    "login.signIn": "登录",
    "login.signingIn": "登录中…",
    "login.invalidCreds": "用户名或密码错误",
    "login.language": "语言",

    # dashboard
    "dashboard.heading": "仪表盘",
    "dashboard.subtitle": "在线监控 - 每 10 秒刷新",
    "dashboard.allOperational": "全部服务正常",
    "dashboard.runChecks": "立即检查",
    "dashboard.running": "运行中…",
    "dashboard.addMonitor": "添加监控",
    "dashboard.lastManualRun": "上次手动运行:",
    "dashboard.total": "全部",
    "dashboard.operational": "正常",
    "dashboard.runningFine": "运行正常",
    "dashboard.down": "宕机",
    "dashboard.needAttention": "需要关注",
    "dashboard.allClear": "无异常",
    "dashboard.pending": "待检查",
    "dashboard.awaitingCheck": "等待首次检查",
    "dashboard.noMonitors": "还没有监控项",
    "dashboard.noMonitorsDesc": "添加第一个监控项，开始跟踪在线状态。",
    "dashboard.createMonitor": "创建监控",
    "dashboard.monitorsWord": "个监控项",
    "dashboard.pendingLabelOne": "{n} 个待检查 — 点击 <strong>{action}</strong> 立即触发首次检查。",
    "dashboard.pendingLabelMany": "{n} 个待检查 — 点击 <strong>{action}</strong> 立即触发首次检查。",

    # monitors list
    "monitors.heading": "监控项",
    "monitors.addMonitor": "添加监控",
    "monitors.searchPlaceholder": "搜索名称、URL、标签…",
    "monitors.allTypes": "所有类型",
    "monitors.allStatuses": "所有状态",
    "monitors.up": "在线",
    "monitors.down": "宕机",
    "monitors.pending": "待检查",
    "monitors.http": "HTTP",
    "monitors.heartbeat": "心跳",
    "monitors.dns": "DNS",
    "monitors.ping": "Ping",
    "monitors.noMatch": "没有符合当前筛选条件的监控项。",
    "monitors.edit": "编辑",
    "monitors.delete": "删除",
    "monitors.configuredOne": "已配置",
    "monitors.configuredMany": "已配置",

    # new / edit monitor
    "newMonitor.back": "← 监控项",
    "newMonitor.heading": "新建监控",
    "newMonitor.subtitle": "配置 HTTP 检查或心跳监控。",
    "editMonitor.back": "← 返回监控",
    "editMonitor.heading": "编辑监控",
    "editMonitor.editNamed": "编辑 - {name}",

    # monitor detail
    "monitor.notFound": "未找到该监控项。",
    "monitor.back": "← 监控项",
    "monitor.checkNow": "立即检查",
    "monitor.checking": "检查中…",
    "monitor.edit": "编辑",
    "monitor.uptime30d": "30 天在线率",
    "monitor.avgResponse": "平均响应 (24h)",
    "monitor.openIncidents": "未处理事件",
    "monitor.lastCheck": "最后检查",
    "monitor.pendingHint": "此监控从未被检查过。生产环境下每分钟自动检查。开发环境请点击上方“立即检查”或执行:",
    "monitor.uptime90d": "90 天在线率",
    "monitor.overallUptime": "整体在线率",
    "monitor.last24h": "最近 24 小时",
    "monitor.last7d": "最近 7 天",
    "monitor.last30d": "最近 30 天",
    "monitor.last90d": "最近 90 天",
    "monitor.responseTime": "响应时间 - 最近 24 小时",
    "monitor.heartbeatUrl": "心跳 URL",
    "monitor.heartbeatUrlDesc": "向该 URL 发送 GET 或 POST 请求以记录一次心跳。",
    "monitor.copy": "复制",
    "monitor.copied": "已复制!",
    "monitor.regen": "重新生成",
    "monitor.regenConfirm": "重新生成心跳令牌? 旧 URL 将失效。",
    "monitor.incidents": "事件",
    "monitor.noIncidents": "无事件 - 一切运行正常。",
    "monitor.resolved": "已解决",
    "monitor.ongoing": "进行中",
    "monitor.recentChecks": "近期检查",
    "monitor.colStatus": "状态",
    "monitor.colTime": "时间",
    "monitor.colResponse": "响应",
    "monitor.colMessage": "信息",
    "monitor.noLogs": "暂无检查日志。",
    "monitor.noLogsPending": "点击“立即检查”触发首次检查。",
    "monitor.resetStats": "重置统计",
    "monitor.resetConfirm": "重置该监控的所有统计? 将删除全部检查日志、事件与在线率数据。",
    "monitor.dangerZone": "危险操作",
    "monitor.enable": "启用",
    "monitor.disable": "禁用",
    "monitor.enableConfirm": "启用该监控? 将恢复检查。",
    "monitor.disableConfirm": "禁用该监控? 将停止检查。",
    "monitor.deleteMonitor": "删除监控",
    "monitor.deleteConfirm": "删除 “{name}”? 此操作无法撤销。",
    "monitor.ongoingFor": "已持续 {duration}",
    "monitor.totalChecks": "总检查次数",
    "monitor.ssl": "SSL",
    "monitor.sslOk": "有效",
    "monitor.sslError": "无效",
    "monitor.sslUnknown": "未检查",
    "monitor.configInterval": "间隔",
    "monitor.configProtocol": "协议",
    "monitor.configMethod": "方法",
    "monitor.configTimeout": "超时",
    "monitor.configHeaders": "请求头",
    "monitor.configCacheBooster": "缓存破坏",
    "monitor.configSslCheck": "SSL 检查",
    "monitor.configDnsHostname": "主机名",
    "monitor.configDnsRecordType": "记录类型",
    "monitor.configDnsExpected": "期望 IP",
    "monitor.prevPage": "← 上一页",
    "monitor.nextPage": "下一页 →",

    # monitor card
    "monitorCard.uptime": "30 天在线率",
    "monitorCard.interval": "间隔",
    "monitorCard.lastCheck": "最后检查",

    # monitor form
    "monitorForm.httpCheck": "HTTP / URL 检查",
    "monitorForm.heartbeat": "心跳",
    "monitorForm.dns": "DNS",
    "monitorForm.ping": "Ping",
    "monitorForm.sectionPing": "Ping 设置",
    "monitorForm.pingUrl": "目标 URL",
    "monitorForm.name": "名称",
    "monitorForm.tags": "标签 (以逗号分隔)",
    "monitorForm.interval": "检查间隔 (秒,最小 60)",
    "monitorForm.sectionRequest": "请求",
    "monitorForm.method": "方法",
    "monitorForm.url": "URL",
    "monitorForm.expectedStatus": "预期状态码",
    "monitorForm.timeout": "超时 (秒)",
    "monitorForm.ipVersion": "IP 版本",
    "monitorForm.ipAuto": "自动",
    "monitorForm.followRedirects": "跟随重定向",
    "monitorForm.authentication": "认证",
    "monitorForm.authNone": "无",
    "monitorForm.authBasic": "Basic",
    "monitorForm.authDigest": "Digest",
    "monitorForm.authBearer": "Bearer Token",
    "monitorForm.authUsername": "用户名",
    "monitorForm.authPassword": "密码",
    "monitorForm.bearerToken": "Bearer Token",
    "monitorForm.headers": "请求头 (每行一个:Key: Value)",
    "monitorForm.requestBody": "请求体 (JSON)",
    "monitorForm.sectionHeartbeat": "心跳设置",
    "monitorForm.expectedEvery": "期望心跳周期 (秒)",
    "monitorForm.gracePeriod": "宽限期 (秒)",
    "monitorForm.tolerateMissed": "容忍缺失心跳数",
    "monitorForm.surgeProtection": "抑制风暴 (触发 N 次告警后暂停)",
    "monitorForm.sslCheck": "验证 SSL 证书",
    "monitorForm.cacheBuster": "缓存破坏 (在 URL 后追加随机参数)",
    "monitorForm.sectionDns": "DNS 设置",
    "monitorForm.dnsResolverUrl": "解析器 URL (DoH)",
    "monitorForm.dnsHostname": "主机名",
    "monitorForm.dnsRecordType": "记录类型",
    "monitorForm.dnsExpectedIp": "期望 IP (可选)",
    "monitorForm.notifications": "通知渠道",
    "monitorForm.notificationsNone": "尚无渠道 - ",
    "monitorForm.notificationsCreate": "创建渠道",
    "monitorForm.notificationsHelp": "选择当该监控状态变化时接收告警的渠道。",
    "monitorForm.notificationRule": "通知规则",
    "monitorForm.notifyAfter": "宕机后 N 次失败发送通知",
    "monitorForm.notifyRepeat": "持续宕机时每 N 次失败重复通知",
    "monitorForm.enabled": "启用",
    "monitorForm.saving": "保存中…",
    "monitorForm.updateMonitor": "更新监控",
    "monitorForm.createMonitor": "创建监控",
    "monitorForm.cancel": "取消",

    # incidents
    "incidents.heading": "事件",
    "incidents.subtitle": "监控项运行历史。",
    "incidents.filterAll": "全部",
    "incidents.filterOngoing": "进行中",
    "incidents.filterResolved": "已解决",
    "incidents.searchPlaceholder": "搜索监控名称或错误信息…",
    "incidents.empty": "没有事件",
    "incidents.emptyDesc": "没有匹配的事件。",
    "incidents.colMonitor": "监控项",
    "incidents.colStatus": "状态",
    "incidents.colStarted": "开始",
    "incidents.colDuration": "持续时间",
    "incidents.colMessage": "信息",
    "incidents.colActions": "操作",
    "incidents.ongoing": "进行中",
    "incidents.resolved": "已解决",
    "incidents.viewMonitor": "查看监控",
    "incidents.delete": "删除",

    # notifications
    "notifications.heading": "通知",
    "notifications.subtitle": "配置监控状态变化时的告警发送渠道。",
    "notifications.addChannel": "添加渠道",
    "notifications.newChannel": "新建渠道",
    "notifications.editChannel": "编辑 - {name}",
    "notifications.empty": "还没有通知渠道",
    "notifications.emptyDesc": "添加一个渠道以便监控宕机时收到告警。",
    "notifications.addFirst": "添加第一个渠道",
    "notifications.active": "启用",
    "notifications.disabled": "已禁用",
    "notifications.edit": "编辑",
    "notifications.delete": "删除",

    # notification form
    "notificationForm.name": "名称",
    "notificationForm.type": "类型",
    "notificationForm.active": "启用",
    "notificationForm.isDefault": "默认(创建新监控时自动选中)",
    "notificationForm.applyToAll": "保存时应用到所有现有监控",
    "notificationForm.saving": "保存中…",
    "notificationForm.saveChanges": "保存修改",
    "notificationForm.createChannel": "创建渠道",
    "notificationForm.sending": "发送中…",
    "notificationForm.sendTest": "发送测试",
    "notificationForm.testSuccess": "测试消息已发送!",
    "notificationForm.cancel": "取消",

    # notification fields
    "notifField.webhookUrl": "Webhook URL",
    "notifField.botToken": "Bot Token",
    "notifField.chatId": "Chat ID",
    "notifField.smtpHost": "SMTP 主机",
    "notifField.smtpPort": "SMTP 端口",
    "notifField.username": "用户名",
    "notifField.password": "密码",
    "notifField.fromAddress": "发件人地址",
    "notifField.toAddresses": "收件人地址",
    "notifField.serverUrl": "服务器 URL",
    "notifField.topic": "主题",
    "notifField.tokenOptional": "Token (可选)",
    "notifField.appToken": "App Token",
    "notifField.userKey": "User Key",
    "notifField.url": "URL",
    "notifField.secretOptional": "Secret (可选)",
    "notifField.appriseApiUrl": "Apprise API URL",
    "notifField.notificationUrls": "通知 URL",
    "notifField.apiTokenOptional": "API Token (可选)",
    "notifField.encryptedPlaceholder": "留空保留已存值",
    "notifField.encryptedHint": "此字段已加密。留空则保留当前值。",

    # status pages
    "statusPages.heading": "状态页",
    "statusPages.subtitle": "展示监控状态的公开页面",
    "statusPages.newPage": "新建页面",
    "statusPages.newStatusPage": "新建状态页",
    "statusPages.labelName": "名称",
    "statusPages.labelSlug": "路径 - URL: /s/{slug}",
    "statusPages.labelSlugEdit": "路径",
    "statusPages.labelDescOpt": "描述 (可选)",
    "statusPages.labelPassword": "密码保护(留空 = 公开)",
    "statusPages.enablePassword": "启用密码保护",
    "statusPages.placeholderPwd": "留空则为公开访问",
    "statusPages.monitorsToDisplay": "显示的监控项",
    "statusPages.showAllMonitors": "显示全部监控 (始终包括当前和未来新增的)",
    "statusPages.noMonitors": "尚未配置任何监控。",
    "statusPages.creating": "保存中…",
    "statusPages.createPage": "创建页面",
    "statusPages.cancel": "取消",
    "statusPages.editPage": "编辑 - {name}",
    "statusPages.labelDesc": "描述",
    "statusPages.labelNewPwd": "新密码",
    "statusPages.pwdHintKeep": "(留空保留,输入空格则移除)",
    "statusPages.pwdHintPublic": "(留空 = 公开)",
    "statusPages.saveChanges": "保存修改",
    "statusPages.loading": "加载中…",
    "statusPages.empty": "还没有状态页",
    "statusPages.emptyDesc": "创建一个公开页面向用户展示服务状态。",
    "statusPages.createFirst": "创建第一个页面",
    "statusPages.passwordProtected": "已加密码",
    "statusPages.copyUrl": "复制链接",
    "statusPages.edit": "编辑",
    "statusPages.delete": "删除",

    # config
    "config.heading": "设置",
    "config.subtitle": "数据保留与行为的全局设置。",
    "config.dataRetention": "数据保留",
    "config.dataRetentionDesc": "超过此期限的状态检查日志将在每次 cron 运行时被自动删除。不影响事件与在线率汇总。",
    "config.keepLogsFor": "日志保留天数",
    "config.days": "天",
    "config.allowedRange": "允许范围: 1–365。默认: 90。",
    "config.saving": "保存中…",
    "config.saved": "已保存",
    "config.save": "保存",
    "config.language": "语言",
    "config.languageDesc": "选择应用与公开状态页的显示语言。",
    "config.backup": "备份与恢复",
    "config.backupDesc": "导出当前配置为文件,可在任意 Pingflare 实例上恢复。",
    "config.exportBackup": "导出备份",
    "config.exporting": "导出中…",
    "config.importBackup": "导入备份",
    "config.importing": "导入中…",
    "config.restoreWarning": "导入将永久覆盖所有监控、通知渠道与状态页。",
    "config.restoreSuccess": "备份恢复成功",
    "config.restoreConfirm": "此操作将永久替换所有现有监控、渠道与状态页,是否继续?",

    # footer
    "footer.updateAvailable": "有可用更新",
    "footer.update": "更新",

    # public status page
    "pub.allOperational": "全部服务正常",
    "pub.outage": "检测到服务中断",
    "pub.degraded": "性能下降",
    "pub.protected": "受保护的状态页",
    "pub.wrongPassword": "密码错误,请重试。",
    "pub.enterPassword": "输入密码",
    "pub.checking": "校验中…",
    "pub.accessPage": "访问页面",
    "pub.activeIncidents": "进行中的事件",
    "pub.started": "开始",
    "pub.services": "服务",
    "pub.noMonitors": "该状态页尚无监控项。",
    "pub.90daysAgo": "90 天前",
    "pub.today": "今天",
    "pub.pastIncidents": "过往事件",
    "pub.noIncidents": "最近 14 天无事件。",
    "pub.poweredBy": "技术支持",
    "pub.updatesEveryMinute": "每分钟更新",
    "pub.statusOperational": "正常",
    "pub.statusOutage": "中断",
    "pub.statusPending": "待检查",
    "pub.uptime": "在线率",
    "pub.noData": "无数据",
    "pub.toLightMode": "切换到浅色模式",
    "pub.toDarkMode": "切换到深色模式",
    "pub.exitFullscreen": "退出全屏",
    "pub.enterFullscreen": "进入全屏",
    "pub.lastChecked": "最后检查",
    "pub.avgResponse": "平均响应",
    "pub.lastResponse": "最新响应",
    "pub.responseHistory": "响应时间 (24 小时)",
    "pub.noResponseData": "无响应数据",
    "pub.24hAgo": "24 小时前",

    # confirm dialogs
    "confirm.deleteMonitor": "删除 “{name}”?",
    "confirm.deleteIncident": "删除事件 “{name}”?",
    "confirm.deleteChannel": "删除渠道 “{name}”?",
    "confirm.deletePage": "删除 “{name}”?",

    # chart
    "chart.notEnoughData": "数据不足",
    "chart.latestMs": "最新 {ms}ms",
    "chart.maxMs": "最高 {ms}ms",

    # time
    "time.never": "从未",
    "time.secondsAgo": "{n} 秒前",
    "time.minutesAgo": "{n} 分钟前",
    "time.hoursAgo": "{n} 小时前",
    "time.daysAgo": "{n} 天前",

    # notify
    "notify.alert": "告警",
    "notify.recovery": "已恢复",
    "notify.reminder": "提醒",
    "notify.callback": "事件",
    "notify.down": "已宕机",
    "notify.up": "已恢复在线",
    "notify.stillDown": "仍处于宕机",
    "notify.responseTime": "响应时间",
    "notify.incidentStarted": "事件开始",
    "notify.url": "URL",
    "notify.heartbeatReceived": "已收到心跳",
    "notify.noHeartbeatYet": "尚未收到心跳",
    "notify.lastHeartbeat": "上次心跳 {n} 秒前",
    "notify.heartbeatOverdue": "心跳超时 {overdue} 秒 (上次 {lastSeen} 秒前)",
    "notify.timeoutAfter": "{n} 秒后超时",

    # monitorForm extras
    "monitorForm.dnsExpectedIpPlaceholder": "例如 93.184.216.34",
    "monitorForm.dnsExpectedIpHint": "如果设置，当响应不包含此值时检查将失败。",
    "monitorForm.sectionAlerts": "告警选项",
    "monitorForm.tolerateFailures": "告警前容忍的失败次数",
    "monitorForm.reminder": "提醒间隔（小时，留空 = 禁用）",
    "monitorForm.sectionNotifications": "通知",
    "monitorForm.noChannels": "尚未配置通知渠道。",
    "monitorForm.addOne": "添加一个",
    "monitorForm.active": "启用",
    "monitorForm.saveChanges": "保存更改",
    "monitorForm.disabled": "已禁用",

    # incidents extras
    "incidents.newIncident": "新建事件",
    "incidents.formTitle": "新建事件",
    "incidents.labelTitle": "标题",
    "incidents.labelStatus": "初始状态",
    "incidents.labelMessage": "初始消息",
    "incidents.placeholderMessage": "我们正在排查错误率升高的问题…",
    "incidents.affectedMonitors": "受影响的监控项（可选）",
    "incidents.noMonitors": "尚未配置监控项。",
    "incidents.creating": "创建中…",
    "incidents.createIncident": "创建事件",
    "incidents.cancel": "取消",
    "incidents.updateTitle": "添加更新",
    "incidents.labelNewStatus": "新状态",
    "incidents.labelUpdateMsg": "消息",
    "incidents.placeholderUpdate": "问题已定位…",
    "incidents.posting": "发布中…",
    "incidents.postUpdate": "发布更新",
    "incidents.loading": "加载中…",
    "incidents.createFirst": "创建你的第一个事件",
    "incidents.started": "开始于",
    "incidents.affects": "影响：",
    "incidents.active": "● 进行中",
    "incidents.addUpdate": "添加更新",

    # incidentStatus
    "incidentStatus.investigating": "排查中",
    "incidentStatus.identified": "已定位",
    "incidentStatus.monitoring": "监控中",
    "incidentStatus.resolved": "已解决",
}

# Sanity check: all English keys must be present in zh
missing = [k for k in en if k not in zh]
extra = [k for k in zh if k not in en]

if missing:
    print(f"[WARN] missing {len(missing)} keys, filling with en fallback:")
    for k in missing:
        print(" -", k, "=", en[k])
        zh[k] = en[k]

if extra:
    print(f"[INFO] dropping {len(extra)} stale keys not in en: {extra}")

# Preserve en's key ordering
zh_ordered = {k: zh[k] for k in en}

with open(zh_path, 'w', encoding='utf-8') as f:
    json.dump(zh_ordered, f, ensure_ascii=False, indent=2)
    f.write('\n')

print(f"[OK] wrote {zh_path} with {len(zh_ordered)} keys")
